### ISSUE TITLE
don't copy my readme

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [rani620/rani620#1]
@rani620

**Comment by MrKrishnaAgarwal** [comment]
![image](https://user-images.githubusercontent.com/100597998/197688285-713791e6-ef7c-4bb0-b889-961d91a75734.png)

see proof

**Comment by MrKrishnaAgarwal** [comment]
don't copy my readme....

**Comment by rani620** [comment]
sorry sir mujhe ye acha laga tha ok i will remove

**Comment by MrKrishnaAgarwal** [comment]
> sorry sir mujhe ye acha laga tha ok i will remove

Remove them right now @rani620
You are copying more
If you don't I have to report to github team
